receivers:
  otlp:
    protocols:
      http:
        endpoint: 0.0.0.0:4318

exporters:
  debug: { }

  otlphttp/tempo:
    endpoint: http://tempo:4318

  zipkin:
    endpoint: http://0.0.0.0:9411

  prometheus:
    endpoint: 0.0.0.0:8889
    const_labels:
      label1: value1

  otlphttp/loki:
    endpoint: http://loki:3100/otlp

extensions:
  health_check:
    endpoint: 0.0.0.0:13133
  pprof:
    endpoint: 0.0.0.0:1777
  zpages:
    endpoint: 0.0.0.0:55679

service:
  extensions: [ health_check, pprof, zpages ]
  pipelines:
    traces:
      receivers: [ otlp ]
      exporters: [ debug, otlphttp/tempo]
    metrics:
      receivers: [ otlp ]
      exporters: [ prometheus ]
    logs:
      receivers: [ otlp ]
      exporters: [ debug, otlphttp/loki ]
